### ISSUE TITLE
Respawn

### ISSUE THREAD

**Issue by shawncplus** [shawncplus/ranviermud#112]
Areas need the ability to respawn their contents on their own timers. Perhaps mobs should individually be able to control their respawn as well. This feature should include the ability to limit the number of a particular mob/item loaded into the game at one time.

This could be approached a couple ways that I could think of:

1. Simple timer once every interval that just immediately spawns in the appropriate number of npcs/items all at once
* A progressive approach that is constantly respawning an area at a computed rate such that if the area was left alone for interval length it would fully respawn.

Personally I prefer the approach 2. It keeps players from sitting around for 10 minutes waiting for a respawn.

**Comment by seanohue** [comment]
>Perhaps mobs should individually be able to control their respawn as well. 

I've thought of doing this as well. I like the idea of having a respawn probability or respawn interval per mob, since some mobs may be rarer than others (I'm thinking mini-bosses or such).

A probability would give the mob a certain chance of spawning per areaRespawnTick (defaulting to 100%).
An interval would say that the mob respawns every number of areaRespawnTicks (defaulting to one).

Let's say you have a super-rare mob that drops a hard to find item, you could limit it to 1 instance total, give it a respawnProbability of 50%, and a respawnInterval of 3. The area's respawnTick is 2 minutes. So if you kill it, there's a good chance it'll respawn within 6-12 minutes but no guarantee.

Alternatively, it could be set up so that the respawnInterval forces it to respawn _at least_ that often, regardless of probability. In that case, there'd be a 50% chance of respawn in the first 5 minutes after killing the mob, but then it'd definitely respawn on the 3rd tick, after 6 minutes.

Either way I like the idea of keeping it configurable at a mob or area level, preferably both.


> A progressive approach that is constantly respawning an area at a computed rate such that if the area was left alone for interval length it would fully respawn.

I agree that this is the most desirable and I think that allowing for mob-level respawn configuration would mimic the progressive approach, as explained above.
