### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by jackjwilliams** [shawncplus/ranviermud#123]
So I used to play Moongate (Materia Magica) and other MUDS years ago, and miss it. I've been looking around at MUD server systems and they are all antiquated except this one. 

I'm no node guru, but I've done plenty of Javascript (and some Node.js development). I started reading the documentation (which is very nice BTW), but was disappointed to see it ends abruptly at Areas.NPC's.

What is the current state of this framework? How can I help as a beginner to the project? Any "easy" issues I could work on?

**Comment by shawncplus** [comment]
I was heavy at work implementing features for the past month so this week I'm going to be updating documentation this week to hopefully be up to date with all the features. Then back to work on features again for the v1.0.0 milestone. I'm always open to outside help so feel free to poke through the open issues and see if there's anything you want to work on

**Comment by seanohue** [comment]
Hi! Thanks for responding. Right now the MUD is at v0.5.0 and is about halfway to a viable release. 

As you mention, the documentation is unfinished and is the current task at hand. Given that, I'd suggest reading through the codebase, cloning it down and booting up a copy of the MUD to play around with a bit. As far as low-hanging issues, the ability to set and get player preferences (autoloot, brief descriptions, etc.) is the only low-hanging fruit I can think of right now but I think @shawncplus might have more suggestions.

Another way to help might be to try to extend and customize the framework, since the end goal is for building a game on top of the base engine to be super easy. Then, if you run into trouble, open an issue and document your experience.

**Comment by jackjwilliams** [comment]
Awesome, I got it running last night and might have found a bug when in combat, after the match was over the server crashed. How do you all debug? I have Visual Studio Code setup with Ubuntu LTS.

**Comment by shawncplus** [comment]
Personally I just use `node --inspect ./ranvier` with NIM https://chrome.google.com/webstore/detail/nim-node-inspector-manage/gnhhdgbaldcilmgcpfddgdbkhjohddkj?hl=en

**Comment by seanohue** [comment]
Debugging? What's that?

Just kidding. I usually just go through the stack trace, but maybe I should use this NIM thing. I also have VS Code with some linters set up.

**Comment by seanohue** [comment]
Also, feel free to join the contributor's Slack team via https://ranviermud.signup.team/ for real-time chatter.
