### ISSUE TITLE
Walkthrough?

### ISSUE THREAD

**Issue by Xarcell** [shawncplus/ranviermud#26]
This isn't an issue, this is a request for help. I'm really wanting to try this out, but I don't know how to get it started. I don't have a server running Node.js so I tried cloud9 and couldn't figure out how to run it.

So I downloaded node.js for windows, and downloaded the ranvier.zip. From there I do not know what to do. Anyone willing to walk me through how to get this running on my local machine so I can play with it? I've Google several tutorials, but I'm not not getting it.

**Comment by ingcake** [comment]
This is all I had to do to get ranvier running on c9.io just now:
1. c9.io>Dashboard>Create new workspace>Clone from url
2. Supply url from your fork and specify that this is a node project (click the node button) > Click "Create"
3. c9.io put the project in workspace, but also added a directory ~/workspace/workspace which I removed.
4. npm install
5. Run as specified in README.txt;; you might want to open a different port, though, e.g.
./ranvier -v --save=10 --respawn=10 --port 8080

**Comment by ingcake** [comment]
Also, npm was happier after I specified a repository in packages.json. You might a similar warning if you don't.

**Comment by Xarcell** [comment]
I got in on cloud9 workspace. How do I log into the game?

**Comment by ingcake** [comment]
Cloud9 provides environment variables that you'll usually want to use instead of specifically naming ports (although I understand that `$PORT` should be 8080)... unless you're only planning to access via localhost. They are `$IP` and `$PORT`.

However, that is not what you want to do in this case, at least for testing purposes. Ranvier doesn't provide an html interface, so you shouldn't attempt to visit `ranvier-xarcell.c9.io`. You'll want to use telnet to access it.
- Open one terminal in your c9 workspace. Run the command I mentioned above, using port 8080, **not** `$PORT`. Leave this open (Ranvier might provide daemon mode, but I haven't looked for it.)
- Open another terminal. Run `telnet localhost 8080` to access the game.

If you *really really* want to host the game (as it's presently distributed) online, then I'm afraid that Cloud9 is not the service you want - Cloud9 is [a development solution, not a hosting platform](https://docs.c9.io/v1.0/discuss/5582d7b8b806360d00244850). For more details on how to use Cloud9, you might want to check out [their documentation](https://docs.c9.io/).

**Comment by Xarcell** [comment]
I managed to get it to the stage where "add npcs to room. done." etc, etc... When I open another terminal and type in "telnet localhost 8080", it just says "bash: telnet: command not found.

**Comment by ingcake** [comment]
In case you're new to Linux, **you should read up on these commands** before you go and use them everywhere. I mean, you absolutely **will** use them all the time, but you should learn the do's and don't's, so to speak. Of course, you won't be able to do too much damage to a fresh Cloud9 VPS. Anyway, this will get you telnet.

`sudo apt-get update`

`sudo apt-get install telnet`

To learn more about using the telnet client, enter `man telnet`.

**Comment by Xarcell** [comment]
Thanks, I was able to play it a bit. It seems to be off to a wonderful start.

I am new to Linux. I've tried using Ubuntu & Fedora, but they will not install on my PC. I have some kinda rare motherboard with a graphics chipset that just isn't compatible with Linux. Even though I've a fan of Ubuntu, I have never used it. So I've never got to practice enough to remember anything.

Thanks for your help.

**Comment by marado** [comment]
This issue should probably be closed.
